version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    restart: unless-stopped
    networks:
      - shared_network

networks:
      shared_network:
        external: true
